[package]
name = "ensub-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
core_engine = { path = "../core_engine" }
crossterm.workspace = true
ensub-theme.workspace = true
language_engine = { path = "../language_engine", features = ["document"] }
ratatui.workspace = true
thiserror.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[dev-dependencies]
tempfile.workspace = true
